In [1]:
import torch
print(torch.__version__)

2.11.0+cu128


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


# creating a tensor

In [5]:
#using empty
a=torch.empty(2,3)

In [6]:
#chceck type
type(a)

torch.Tensor

In [7]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
#usig rand
torch.rand(2,3)

tensor([[0.1060, 0.0889, 0.5131],
        [0.7982, 0.1950, 0.4943]])

In [10]:
#use of seed
#manual seed
torch.manual_seed(100)
torch.rand(2,3)



tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(3))

# using full
print("using full ->", torch.full((3, 3), 10))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


# tensor shapes

In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [30]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# tensor data types


In [23]:
#find datatype
x.dtype


torch.int64

In [25]:
#assign datatype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# mathematical operations


# 1. scalar operation

In [31]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [33]:
#addition
x+2
#subtraction
x-3
#multiplication
x*4
#divison
x/3
#int division
(x*100)//3
#mod
((x*100)//3)%2
#power
x**2


tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# 2. element wise operation

In [34]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [36]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])

In [37]:
c=torch.tensor([1,-3,2,-4])

In [38]:
#absolute value
torch.abs(c)

tensor([1, 3, 2, 4])

In [39]:
#negative
torch.neg(c)

tensor([-1,  3, -2,  4])

In [40]:
d = torch.tensor([1.5, 2.7, 5.7, 4.4])

In [41]:
#round
torch.round(d)

tensor([2., 3., 6., 4.])

In [42]:
#ceil
torch.ceil(d)

tensor([2., 3., 6., 5.])

In [43]:
#floor
torch.floor(d)

tensor([1., 2., 5., 4.])

In [44]:
#clamp
torch.clamp(d,min=2,max=4)


tensor([2.0000, 2.7000, 4.0000, 4.0000])

# 3.reduction operation

In [45]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [47]:
#sum
torch.sum(e)
#sum along columns
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)

tensor([15.,  9.])

In [48]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [49]:
#median
torch.median(e)

tensor(0.)

In [50]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [51]:
#prodcut
torch.prod(e)

tensor(0.)

In [53]:
# standard deviation
torch.std(e)


tensor(4.4272)

In [54]:
# variance
torch.var(e)

tensor(19.6000)

In [55]:
# argmax
torch.argmax(e)

tensor(5)

In [56]:
# argmin
torch.argmin(e)

tensor(1)

# 4.matrix operations

In [57]:
 f= torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [58]:
#matrix multiplication
torch.matmul(f,g)

tensor([[ 87, 119],
        [ 65,  99]])

In [60]:
vector1=torch.tensor([1,3])
vector2=torch.tensor([2,4])
#dot product
torch.dot(vector1,vector2)

tensor(14)

In [74]:
f

tensor([[5, 7, 3],
        [9, 4, 0]])

In [61]:
#transppose
torch.transpose(f,0,1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [62]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [63]:
# determinant
torch.det(h)

tensor(-110.)

In [64]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

# 5.comparison operators


In [65]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)



tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [66]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

# 6. special functions

In [67]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [68]:
# log
torch.log(k)

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

In [69]:
# exp
torch.exp(k)

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

In [70]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

In [71]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

In [72]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

In [73]:
#relu
torch.relu(k)

tensor([[3., 3., 5.],
        [0., 6., 4.]])

# 7.inplace operations

In [75]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [76]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [77]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [78]:
n

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])

In [79]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [80]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [81]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

# copying  a tensor

In [82]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [83]:
b=a

In [84]:
b

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [85]:
a[0][0]=0

In [86]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [87]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [88]:
id(a)

2344015215520

In [89]:
id(b)

2344015215520

In [90]:
b=a.clone()

In [91]:
a

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [92]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [93]:
a[0][0] = 10

In [94]:
a

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

In [95]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [96]:
id(a)

2344015215520

In [97]:
id(b)

2344146791584

# tensor operation on gpu

In [98]:
torch.cuda.is_available()

True

In [99]:
device=torch.device('cuda')

In [100]:
#creating a new tensor on gpu
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [102]:
#moving an existing tensor to gpu
a=torch.rand(2,3)
a

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [104]:
b=a.to(device)

In [105]:
b+5

tensor([[5.9186, 5.2131, 5.3957],
        [5.6017, 5.4234, 5.5224]], device='cuda:0')

In [107]:
import torch
import time

# Define the size of the matrices
size = 10000  # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2)  # Matrix multiplication on GPU
torch.cuda.synchronize()  # Ensure all GPU operations are complete
gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")
#compare results
print("\nspeedup (CPU time/  GPU time):",cpu_time/ gpu_time)


Time on CPU: 4.8703 seconds
Time on GPU: 0.3500 seconds

speedup (CPU time/  GPU time): 13.915128759165457


# reshaping tensors

In [108]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [109]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [110]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [111]:
b=torch.rand(2,3,4)
b


tensor([[[0.0083, 0.0504, 0.1486, 0.8395],
         [0.8331, 0.4379, 0.4083, 0.5009],
         [0.4067, 0.9891, 0.1025, 0.9936]],

        [[0.3642, 0.8499, 0.3817, 0.2436],
         [0.1008, 0.1176, 0.3651, 0.4549],
         [0.8776, 0.3721, 0.7827, 0.4926]]])

In [113]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [115]:
#unsqueeze
#image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [117]:
#squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# numpy and pytorch

In [119]:
import numpy as np

In [121]:
a=torch.tensor([1,2,3])
a


tensor([1, 2, 3])

In [122]:
b=a.numpy()

In [123]:
b

array([1, 2, 3])

In [124]:
type(b)

numpy.ndarray

In [126]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [127]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [1]:
!git --version

git version 2.53.0.windows.2


In [2]:
import os
print(os.getcwd())

C:\Users\Radhika


In [4]:
import os
print(os.path.abspath("tensors-with-pytorch.ipynb"))

C:\Users\Radhika\tensors-with-pytorch.ipynb


In [ ]:
!git init
!git add .
!git commit -m "Initial commit"
!git branch -M main
!git remote add origin https://github.com/radhikarajput0410-wq/PyTorch.git
!git push -u origin main

Reinitialized existing Git repository in C:/Users/Radhika/.git/
